### ISSUE TITLE
[Bug] TF2_GetPlayerLoadoutSlot doesn't return 2/3 cosmetics nor any taunts

### ISSUE THREAD

**Issue by godrider** [nosoop/sourcemod-tf2wearables#4]
I can't get the entities of slot 7 (TF2LoadoutSlot_Misc1) and 10 (TF2LoadoutSlot_Misc3) despite having cosmetics in these slots.
It also doesn't seem to get any taunts whatsoever.

Loadout: [weapons](https://i.imgur.com/fxjHSA2.png) and [taunts](https://i.imgur.com/4bdQavL.png)
```
] checkmyitems 
Processed items for GodRider
GodRider Item Slot 0: ent 67, class "tf_weapon_sniperrifle", index 230
GodRider Item Slot 1: ent 64, class "tf_weapon_jar", index 58
GodRider Item Slot 2: ent 65, class "tf_weapon_club", index 232
GodRider Item Slot 8: ent 70, class "tf_wearable", index 279 // _Misc2  = Ghastly Gibus
GodRider Item Slot 9: ent 76, class "tf_wearable", index 241 // _Action = Duel MiniGame
```

Is this a bug? Or a limitation perhaps? If so, any good alternatives?

**Comment by nosoop** [comment]
Yeah, that's a limitation of the function being used &mdash; taunts do not exist as real entities (anymore), and the function returns on the first matching wearable item matching the loadout slot specified in the item schema (hat / misc).  It looks like the function also treats head slots as identical to misc slots (prior to Smissmas 2013, they were considered distinct), so there is no hat / misc distinction; it'll just grab whichever one it sees first.

For wearable entities, [tf2utils provides `TF2Util_GetPlayerWearable()` and `TF2Util_GetPlayerWearableCount()` natives](https://github.com/nosoop/SM-TFUtils/blob/5cdaadb12808b3a9894a0b917e2d1365c970e0be/scripting/include/tf2utils.inc#L145-L154), which can be used to access the underlying `m_hMyWearables` array.  tf2utils is intended as a more feature-filled replacement to tf2wearables; its `TF2Util_GetPlayerLoadoutEntity()` is an exact copy of `TF2_GetPlayerLoadoutSlot()`.

You can get a raw `CEconItemView*` (the item-specific data; this is not an entity) by calling `CTFPlayer::GetLoadoutItem()` directly and read the itemdef index from that; that'd be the only way to get the taunt, and it'd also allow you to identify which cosmetic slot has a particular item.

**Comment by nosoop** [comment]
Going to go ahead and close this &mdash; if you'd like to see that sort of functionality added to tf2utils, you're very much welcome to create an issue there.  I can't promise I'll work on it (though monetary incentives help), but it does seem like a good fit and should be completely doable.
